### ISSUE TITLE
clover引导出现了禁止标志

### ISSUE THREAD

**Issue by meeteason** [kkzzhizhou/Dell-3443-Hackintosh#1]
屏幕：1366x768 原装屏
硬盘：ssd + 机械（拆了光驱装的）

Bios已开启AHCI

进入Clover引导，没有出现进度条，然后就出现了禁止标志
![禁止标志拍照](https://user-images.githubusercontent.com/38457612/43378440-9ac25896-93f9-11e8-9e38-be422e66ed2e.png)

**Comment by kkzzhizhou** [comment]
引导界面按空格，选择-verbose模式，将报错信息贴上来

**Comment by meeteason** [comment]
感谢回复。报错如下：
![img_20180814_203445](https://user-images.githubusercontent.com/38457612/44145670-17781f70-a0bf-11e8-849e-3b54e27bce4d.jpg)

**Comment by kkzzhizhou** [comment]
启动参数添加-f UseKernelCache=No
如果不了解操作的话可以加群问:688324116(一起黑苹果)
也可以加我的QQ:806508401
